# Generated by Django 5.2.17 on 2026-09-10 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'categoría',
                'verbose_name_plural': 'categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=64, unique=True, verbose_name='código')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
            ],
            options={
                'verbose_name': 'container',
                'verbose_name_plural': 'containers',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(max_length=32, unique=True, verbose_name='NIT')),
                ('camara_comercio', models.CharField(max_length=120, verbose_name='registro de cámara de comercio')),
                ('nombre', models.CharField(max_length=200, verbose_name='nombre de la empresa')),
                ('representante_legal', models.CharField(max_length=200, verbose_name='representante legal')),
                ('contacto', models.CharField(max_length=120, verbose_name='contacto')),
                ('correo', models.EmailField(max_length=254, verbose_name='correo')),
            ],
            options={
                'verbose_name': 'empresa',
                'verbose_name_plural': 'empresas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='nombre')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='inventario.categoria', verbose_name='categoría')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(verbose_name='cantidad')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entregas', to='inventario.container', verbose_name='container')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entregas', to='inventario.empresa', verbose_name='empresa')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entregas', to='inventario.producto', verbose_name='producto')),
            ],
            options={
                'verbose_name': 'entrega',
                'verbose_name_plural': 'entregas',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(verbose_name='cantidad')),
                ('costo_base', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='costo base')),
                ('iva', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='IVA')),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='precio de venta')),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='inventario.container', verbose_name='container')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventario', to='inventario.producto', verbose_name='producto')),
            ],
            options={
                'verbose_name': 'inventario',
                'verbose_name_plural': 'inventarios',
                'ordering': ['producto__nombre'],
                'unique_together': {('container', 'producto')},
            },
        ),
    ]
