# Generated by Django 5.2.17 — carrito, factura, empresa.usuario

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="empresa",
            name="usuario",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="empresa",
                to=settings.AUTH_USER_MODEL,
                verbose_name="usuario",
            ),
        ),
        migrations.CreateModel(
            name="Carrito",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("abierto", models.BooleanField(default=True, verbose_name="abierto")),
                ("creado", models.DateTimeField(auto_now_add=True, verbose_name="creado")),
                (
                    "container",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="carritos",
                        to="inventario.container",
                        verbose_name="container",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carritos",
                        to="inventario.empresa",
                        verbose_name="empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "carrito",
                "verbose_name_plural": "carritos",
                "ordering": ["-creado"],
            },
        ),
        migrations.CreateModel(
            name="Factura",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("numero", models.CharField(max_length=32, unique=True, verbose_name="número")),
                ("total", models.DecimalField(decimal_places=2, max_digits=14, verbose_name="total")),
                ("creado", models.DateTimeField(auto_now_add=True, verbose_name="creado")),
                (
                    "carrito",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="factura",
                        to="inventario.carrito",
                        verbose_name="carrito",
                    ),
                ),
                (
                    "container",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="facturas",
                        to="inventario.container",
                        verbose_name="container",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="facturas",
                        to="inventario.empresa",
                        verbose_name="empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "factura",
                "verbose_name_plural": "facturas",
                "ordering": ["-creado"],
            },
        ),
        migrations.CreateModel(
            name="LineaCarrito",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("cantidad", models.PositiveIntegerField(default=1, verbose_name="cantidad")),
                (
                    "precio_unitario",
                    models.DecimalField(decimal_places=2, max_digits=14, verbose_name="precio unitario"),
                ),
                (
                    "carrito",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lineas",
                        to="inventario.carrito",
                        verbose_name="carrito",
                    ),
                ),
                (
                    "inventario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lineas_carrito",
                        to="inventario.inventario",
                        verbose_name="inventario",
                    ),
                ),
            ],
            options={
                "verbose_name": "línea de carrito",
                "verbose_name_plural": "líneas de carrito",
                "unique_together": {("carrito", "inventario")},
            },
        ),
        migrations.CreateModel(
            name="LineaFactura",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("cantidad", models.PositiveIntegerField(verbose_name="cantidad")),
                (
                    "precio_unitario",
                    models.DecimalField(decimal_places=2, max_digits=14, verbose_name="precio unitario"),
                ),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=14, verbose_name="subtotal")),
                (
                    "factura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lineas",
                        to="inventario.factura",
                        verbose_name="factura",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lineas_factura",
                        to="inventario.producto",
                        verbose_name="producto",
                    ),
                ),
            ],
            options={
                "verbose_name": "línea de factura",
                "verbose_name_plural": "líneas de factura",
            },
        ),
    ]
