"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.17.
"""

import os
from pathlib import Path

from django.templatetags.static import static
from django.urls import reverse_lazy

BASE_DIR = Path(__file__).resolve().parent.parent


SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-l#_^eej5t6g_lii8&wphj$1+u%2d0y6u5n)+3fcqc&7c)z68no",
)

# Local: DEBUG=1. En PythonAnywhere poner DJANGO_DEBUG=0 en el WSGI.
DEBUG = os.environ.get("DJANGO_DEBUG", "1") == "1"

PA_HOST = "WilmanMontenegro.pythonanywhere.com"
ALLOWED_HOSTS = [
    "127.0.0.1",
    "localhost",
    "testserver",
    PA_HOST,
]
CSRF_TRUSTED_ORIGINS = [
    f"https://{PA_HOST}",
]

LOGIN_URL = "entrar"
LOGIN_REDIRECT_URL = "catalogo"
LOGOUT_REDIRECT_URL = "entrar"

INSTALLED_APPS = [
    "inventario.apps.InventarioConfig",  # index.html propio antes de Unfold
    "unfold",
    "unfold.contrib.filters",
    "unfold.contrib.forms",
    "unfold.contrib.inlines",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

LANGUAGE_CODE = "es-co"
LANGUAGES = [
    ("es-co", "Español (Colombia)"),
]
TIME_ZONE = "America/Bogota"
USE_I18N = True
USE_TZ = True

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"
LOCALE_PATHS = [BASE_DIR / "locale"]
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Acento aguamarina (#0d9488) — escala OKLCH para Unfold
# Marca empresa: Eureka s&s S.A.S
UNFOLD = {
    "SITE_TITLE": "Eureka s&s",
    "SITE_HEADER": "Eureka s&s",
    "SITE_SUBHEADER": "Container → empresa",
    "SITE_URL": "/",
    "SITE_ICON": {
        "light": lambda request: static("inventario/brand/eureka-mark.png"),
        "dark": lambda request: static("inventario/brand/eureka-mark.png"),
    },
    "SHOW_HISTORY": False,
    "SHOW_VIEW_ON_SITE": False,
    "BORDER_RADIUS": "10px",
    "THEME": "light",
    "DASHBOARD_CALLBACK": "inventario.admin_dashboard.dashboard_callback",
    "STYLES": [
        "inventario.admin_dashboard.unfold_stylesheet",
    ],
    "COLORS": {
        "primary": {
            "50": "oklch(98% 0.02 185)",
            "100": "oklch(95% 0.04 185)",
            "200": "oklch(90% 0.06 185)",
            "300": "oklch(83% 0.09 185)",
            "400": "oklch(72% 0.11 185)",
            "500": "oklch(62% 0.12 185)",
            "600": "oklch(55% 0.12 185)",
            "700": "oklch(48% 0.11 185)",
            "800": "oklch(40% 0.09 185)",
            "900": "oklch(33% 0.07 185)",
            "950": "oklch(25% 0.05 185)",
        },
    },
    "SIDEBAR": {
        "show_search": False,
        "show_all_applications": False,
        "navigation": [
            {
                "title": "Carga",
                "separator": True,
                "items": [
                    {
                        "title": "Inicio",
                        "icon": "dashboard",
                        "link": reverse_lazy("admin:index"),
                    },
                    {
                        "title": "Containers",
                        "icon": "deployed_code",
                        "link": reverse_lazy("admin:inventario_container_changelist"),
                    },
                    {
                        "title": "Productos",
                        "icon": "devices",
                        "link": reverse_lazy("admin:inventario_producto_changelist"),
                    },
                    {
                        "title": "Inventario",
                        "icon": "warehouse",
                        "link": reverse_lazy("admin:inventario_inventario_changelist"),
                    },
                    {
                        "title": "Categorías",
                        "icon": "category",
                        "link": reverse_lazy("admin:inventario_categoria_changelist"),
                    },
                ],
            },
            {
                "title": "Ventas",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "Empresas",
                        "icon": "storefront",
                        "link": reverse_lazy("admin:inventario_empresa_changelist"),
                    },
                    {
                        "title": "Facturas",
                        "icon": "receipt_long",
                        "link": reverse_lazy("admin:inventario_factura_changelist"),
                    },
                    {
                        "title": "Carritos",
                        "icon": "shopping_cart",
                        "link": reverse_lazy("admin:inventario_carrito_changelist"),
                    },
                ],
            },
            {
                "title": "Sistema",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "Usuarios",
                        "icon": "person",
                        "link": reverse_lazy("admin:auth_user_changelist"),
                    },
                ],
            },
        ],
    },
}
